//
//  CwlOutlineView_macOS.swift
//  CwlViews
//
//  Created by Matt Gallagher on 28/10/2015.
//  Copyright © 2015 Matt Gallagher ( https://www.cocoawithlove.com ). All rights reserved.
//
//  Permission to use, copy, modify, and/or distribute this software for any purpose with or without
//  fee is hereby granted, provided that the above copyright notice and this permission notice
//  appear in all copies.
//
//  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
//  SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
//  AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
//  NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
//  OF THIS SOFTWARE.
//

#if os(macOS)

extension BindingParser where Binding: OutlineViewBinding {
	// You can easily convert the `Binding` cases to `BindingParser` using the following Xcode-style regex:
	// Replace: case ([^\(]+)\((.+)\)$
	// With:    public static var $1: BindingParser<$2, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<$2, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<$2> in if case .$1(let x) = binding { return x } else { return nil } }) }
		
	//	0. Static bindings are applied at construction and are subsequently immutable.
	
	// 1. Value bindings may be applied at construction and may subsequently change.
	public static var allowsColumnReordering: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnReordering(let x) = binding { return x } else { return nil } }) }
	public static var allowsColumnResizing: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnResizing(let x) = binding { return x } else { return nil } }) }
	public static var allowsColumnSelection: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnSelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsEmptySelection: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsEmptySelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsMultipleSelection: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsMultipleSelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsTypeSelect: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsTypeSelect(let x) = binding { return x } else { return nil } }) }
	public static var autoresizesOutlineColumn: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .autoresizesOutlineColumn(let x) = binding { return x } else { return nil } }) }
	public static var autosaveExpandedItems: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .autosaveExpandedItems(let x) = binding { return x } else { return nil } }) }
	public static var autosaveName: BindingParser<Dynamic<NSTableView.AutosaveName?>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.AutosaveName?>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.AutosaveName?>> in if case .autosaveName(let x) = binding { return x } else { return nil } }) }
	public static var autosaveTableColumns: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .autosaveTableColumns(let x) = binding { return x } else { return nil } }) }
	public static var backgroundColor: BindingParser<Dynamic<NSColor>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSColor>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSColor>> in if case .backgroundColor(let x) = binding { return x } else { return nil } }) }
	public static var columnAutoresizingStyle: BindingParser<Dynamic<NSTableView.ColumnAutoresizingStyle>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.ColumnAutoresizingStyle>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.ColumnAutoresizingStyle>> in if case .columnAutoresizingStyle(let x) = binding { return x } else { return nil } }) }
	public static var columns: BindingParser<Dynamic<[TableColumn<Binding.NodeDataType>]>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<[TableColumn<Binding.NodeDataType>]>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<[TableColumn<Binding.NodeDataType>]>> in if case .columns(let x) = binding { return x } else { return nil } }) }
	public static var cornerView: BindingParser<Dynamic<ViewConvertible?>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<ViewConvertible?>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<ViewConvertible?>> in if case .cornerView(let x) = binding { return x } else { return nil } }) }
	public static var draggingDestinationFeedbackStyle: BindingParser<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>> in if case .draggingDestinationFeedbackStyle(let x) = binding { return x } else { return nil } }) }
	public static var floatsGroupRows: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .floatsGroupRows(let x) = binding { return x } else { return nil } }) }
	public static var gridColor: BindingParser<Dynamic<NSColor>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSColor>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSColor>> in if case .gridColor(let x) = binding { return x } else { return nil } }) }
	public static var gridStyleMask: BindingParser<Dynamic<NSTableView.GridLineStyle>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.GridLineStyle>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.GridLineStyle>> in if case .gridStyleMask(let x) = binding { return x } else { return nil } }) }
	public static var headerView: BindingParser<Dynamic<TableHeaderViewConvertible?>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<TableHeaderViewConvertible?>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<TableHeaderViewConvertible?>> in if case .headerView(let x) = binding { return x } else { return nil } }) }
	public static var indentationMarkerFollowsCell: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .indentationMarkerFollowsCell(let x) = binding { return x } else { return nil } }) }
	public static var indentationPerLevel: BindingParser<Dynamic<CGFloat>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<CGFloat>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<CGFloat>> in if case .indentationPerLevel(let x) = binding { return x } else { return nil } }) }
	public static var intercellSpacing: BindingParser<Dynamic<NSSize>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSSize>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSSize>> in if case .intercellSpacing(let x) = binding { return x } else { return nil } }) }
	public static var outlineTableColumnIdentifier: BindingParser<Dynamic<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSUserInterfaceItemIdentifier>> in if case .outlineTableColumnIdentifier(let x) = binding { return x } else { return nil } }) }
	public static var rowHeight: BindingParser<Dynamic<CGFloat>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<CGFloat>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<CGFloat>> in if case .rowHeight(let x) = binding { return x } else { return nil } }) }
	public static var rowSizeStyle: BindingParser<Dynamic<NSTableView.RowSizeStyle>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.RowSizeStyle>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.RowSizeStyle>> in if case .rowSizeStyle(let x) = binding { return x } else { return nil } }) }
	public static var selectionHighlightStyle: BindingParser<Dynamic<NSTableView.SelectionHighlightStyle>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSTableView.SelectionHighlightStyle>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.SelectionHighlightStyle>> in if case .selectionHighlightStyle(let x) = binding { return x } else { return nil } }) }
	public static var stronglyReferencesItems: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .stronglyReferencesItems(let x) = binding { return x } else { return nil } }) }
	public static var treeData: BindingParser<Dynamic<TreeAnimation<Binding.NodeDataType>>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<TreeAnimation<Binding.NodeDataType>>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<TreeAnimation<Binding.NodeDataType>>> in if case .treeData(let x) = binding { return x } else { return nil } }) }
	public static var userInterfaceLayoutDirection: BindingParser<Dynamic<NSUserInterfaceLayoutDirection>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<NSUserInterfaceLayoutDirection>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSUserInterfaceLayoutDirection>> in if case .userInterfaceLayoutDirection(let x) = binding { return x } else { return nil } }) }
	public static var usesAlternatingRowBackgroundColors: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .usesAlternatingRowBackgroundColors(let x) = binding { return x } else { return nil } }) }
	public static var verticalMotionCanBeginDrag: BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Dynamic<Bool>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .verticalMotionCanBeginDrag(let x) = binding { return x } else { return nil } }) }
	
	// 2. Signal bindings are performed on the object after construction.
	public static var collapseIndexPath: BindingParser<Signal<(indexPath: IndexPath?, collapseChildren: Bool)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexPath: IndexPath?, collapseChildren: Bool)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexPath: IndexPath?, collapseChildren: Bool)>> in if case .collapseIndexPath(let x) = binding { return x } else { return nil } }) }
	public static var deselectAll: BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .deselectAll(let x) = binding { return x } else { return nil } }) }
	public static var deselectColumn: BindingParser<Signal<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier>> in if case .deselectColumn(let x) = binding { return x } else { return nil } }) }
	public static var deselectIndexPath: BindingParser<Signal<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<IndexPath>> in if case .deselectIndexPath(let x) = binding { return x } else { return nil } }) }
	public static var expandIndexPath: BindingParser<Signal<(indexPath: IndexPath?, expandChildren: Bool)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexPath: IndexPath?, expandChildren: Bool)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexPath: IndexPath?, expandChildren: Bool)>> in if case .expandIndexPath(let x) = binding { return x } else { return nil } }) }
	public static var hideRowActions: BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .hideRowActions(let x) = binding { return x } else { return nil } }) }
	public static var hideRows: BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>> in if case .hideRows(let x) = binding { return x } else { return nil } }) }
	public static var highlightColumn: BindingParser<Signal<NSUserInterfaceItemIdentifier?>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier?>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier?>> in if case .highlightColumn(let x) = binding { return x } else { return nil } }) }
	public static var moveColumn: BindingParser<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>> in if case .moveColumn(let x) = binding { return x } else { return nil } }) }
	public static var scrollColumnToVisible: BindingParser<Signal<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier>> in if case .scrollColumnToVisible(let x) = binding { return x } else { return nil } }) }
	public static var scrollIndexPathToVisible: BindingParser<Signal<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<IndexPath>> in if case .scrollIndexPathToVisible(let x) = binding { return x } else { return nil } }) }
	public static var selectAll: BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .selectAll(let x) = binding { return x } else { return nil } }) }
	public static var selectColumns: BindingParser<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>> in if case .selectColumns(let x) = binding { return x } else { return nil } }) }
	public static var selectIndexPaths: BindingParser<Signal<(indexPaths: Set<IndexPath>, byExtendingSelection: Bool)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexPaths: Set<IndexPath>, byExtendingSelection: Bool)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexPaths: Set<IndexPath>, byExtendingSelection: Bool)>> in if case .selectIndexPaths(let x) = binding { return x } else { return nil } }) }
	public static var setDropIndexPath: BindingParser<Signal<(indexPath: IndexPath?, dropChildIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexPath: IndexPath?, dropChildIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexPath: IndexPath?, dropChildIndex: Int)>> in if case .setDropIndexPath(let x) = binding { return x } else { return nil } }) }
	public static var sizeLastColumnToFit: BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .sizeLastColumnToFit(let x) = binding { return x } else { return nil } }) }
	public static var sizeToFit: BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .sizeToFit(let x) = binding { return x } else { return nil } }) }
	public static var unhideRows: BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>> in if case .unhideRows(let x) = binding { return x } else { return nil } }) }
	
	// 3. Action bindings are triggered by the object after construction.
	public static var columnMoved: BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>> in if case .columnMoved(let x) = binding { return x } else { return nil } }) }
	public static var columnResized: BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>> in if case .columnResized(let x) = binding { return x } else { return nil } }) }
	public static var doubleAction: BindingParser<TargetAction, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<TargetAction, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<TargetAction> in if case .doubleAction(let x) = binding { return x } else { return nil } }) }
	public static var selectionChanged: BindingParser<SignalInput<(selectedColumns: Set<NSUserInterfaceItemIdentifier>, selectedIndexPaths: Set<IndexPath>)>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<(selectedColumns: Set<NSUserInterfaceItemIdentifier>, selectedIndexPaths: Set<IndexPath>)>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<(selectedColumns: Set<NSUserInterfaceItemIdentifier>, selectedIndexPaths: Set<IndexPath>)>> in if case .selectionChanged(let x) = binding { return x } else { return nil } }) }
	public static var selectionIsChanging: BindingParser<SignalInput<Void>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<Void>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<Void>> in if case .selectionIsChanging(let x) = binding { return x } else { return nil } }) }
	public static var indexPathDidCollapse: BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<IndexPath>> in if case .indexPathDidCollapse(let x) = binding { return x } else { return nil } }) }
	public static var indexPathDidExpand: BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<IndexPath>> in if case .indexPathDidExpand(let x) = binding { return x } else { return nil } }) }
	public static var indexPathWillCollapse: BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<IndexPath>> in if case .indexPathWillCollapse(let x) = binding { return x } else { return nil } }) }
	public static var indexPathWillExpand: BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<IndexPath>> in if case .indexPathWillExpand(let x) = binding { return x } else { return nil } }) }
	public static var visibleIndexPathsChanged: BindingParser<SignalInput<Set<IndexPath>>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<SignalInput<Set<IndexPath>>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<SignalInput<Set<IndexPath>>> in if case .visibleIndexPathsChanged(let x) = binding { return x } else { return nil } }) }
	
	// 4. Delegate bindings require synchronous evaluation within the object's context.
	public static var acceptDrop: BindingParser<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ indexPath: IndexPath?, _ childIndex: Int) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ indexPath: IndexPath?, _ childIndex: Int) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ indexPath: IndexPath?, _ childIndex: Int) -> Bool> in if case .acceptDrop(let x) = binding { return x } else { return nil } }) }
	public static var didClickTableColumn: BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(NSOutlineView, NSTableColumn) -> Void> in if case .didClickTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var didDragTableColumn: BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(NSOutlineView, NSTableColumn) -> Void> in if case .didDragTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var draggingSessionEnded: BindingParser<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void> in if case .draggingSessionEnded(let x) = binding { return x } else { return nil } }) }
	public static var draggingSessionWillBegin: BindingParser<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ willBeginAt: NSPoint, _ forItems: [IndexPath]) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ willBeginAt: NSPoint, _ forItems: [IndexPath]) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ draggingSession: NSDraggingSession, _ willBeginAt: NSPoint, _ forItems: [IndexPath]) -> Void> in if case .draggingSessionWillBegin(let x) = binding { return x } else { return nil } }) }
	public static var groupRowCellConstructor: BindingParser<(Int) -> TableCellViewConvertible, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(Int) -> TableCellViewConvertible, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(Int) -> TableCellViewConvertible> in if case .groupRowCellConstructor(let x) = binding { return x } else { return nil } }) }
	public static var heightOfRow: BindingParser<(NSOutlineView, _ indexPath: IndexPath) -> CGFloat, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(NSOutlineView, _ indexPath: IndexPath) -> CGFloat, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(NSOutlineView, _ indexPath: IndexPath) -> CGFloat> in if case .heightOfRow(let x) = binding { return x } else { return nil } }) }
	public static var isIndexPathExpandable: BindingParser<(_ outlineView: NSOutlineView, IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, IndexPath) -> Bool> in if case .isIndexPathExpandable(let x) = binding { return x } else { return nil } }) }
	public static var mouseDownInHeaderOfTableColumn: BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(NSOutlineView, NSTableColumn) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(NSOutlineView, NSTableColumn) -> Void> in if case .mouseDownInHeaderOfTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var nextTypeSelectMatch: BindingParser<(_ outlineView: NSOutlineView, _ from: IndexPath, _ to: IndexPath, _ for: String) -> IndexPath?, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ from: IndexPath, _ to: IndexPath, _ for: String) -> IndexPath?, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ from: IndexPath, _ to: IndexPath, _ for: String) -> IndexPath?> in if case .nextTypeSelectMatch(let x) = binding { return x } else { return nil } }) }
	public static var pasteboardWriter: BindingParser<(_ outlineView: NSOutlineView, _ forIndexPath: IndexPath) -> NSPasteboardWriting?, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ forIndexPath: IndexPath) -> NSPasteboardWriting?, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ forIndexPath: IndexPath) -> NSPasteboardWriting?> in if case .pasteboardWriter(let x) = binding { return x } else { return nil } }) }
	public static var rowView: BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> TableRowViewConvertible?, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> TableRowViewConvertible?, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> TableRowViewConvertible?> in if case .rowView(let x) = binding { return x } else { return nil } }) }
	public static var selectionIndexesForProposedSelection: BindingParser<(_ outlineView: NSOutlineView, _ proposedSelectionIndexes: Set<IndexPath>) -> Set<IndexPath>, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ proposedSelectionIndexes: Set<IndexPath>) -> Set<IndexPath>, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ proposedSelectionIndexes: Set<IndexPath>) -> Set<IndexPath>> in if case .selectionIndexesForProposedSelection(let x) = binding { return x } else { return nil } }) }
	public static var selectionShouldChange: BindingParser<(_ outlineView: NSOutlineView) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView) -> Bool> in if case .selectionShouldChange(let x) = binding { return x } else { return nil } }) }
	public static var shouldCollapse: BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool> in if case .shouldCollapse(let x) = binding { return x } else { return nil } }) }
	public static var shouldExpand: BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool> in if case .shouldExpand(let x) = binding { return x } else { return nil } }) }
	public static var shouldReorderColumn: BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn, _ newIndex: Int) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn, _ newIndex: Int) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ column: NSTableColumn, _ newIndex: Int) -> Bool> in if case .shouldReorderColumn(let x) = binding { return x } else { return nil } }) }
	public static var shouldSelectIndexPath: BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ indexPath: IndexPath) -> Bool> in if case .shouldSelectIndexPath(let x) = binding { return x } else { return nil } }) }
	public static var shouldSelectTableColumn: BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn?) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn?) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ column: NSTableColumn?) -> Bool> in if case .shouldSelectTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var shouldTypeSelectForEvent: BindingParser<(_ outlineView: NSOutlineView, _ event: NSEvent, _ searchString: String?) -> Bool, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ event: NSEvent, _ searchString: String?) -> Bool, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ event: NSEvent, _ searchString: String?) -> Bool> in if case .shouldTypeSelectForEvent(let x) = binding { return x } else { return nil } }) }
	public static var sizeToFitWidthOfColumn: BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn) -> CGFloat, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn) -> CGFloat, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ column: NSTableColumn) -> CGFloat> in if case .sizeToFitWidthOfColumn(let x) = binding { return x } else { return nil } }) }
	public static var sortDescriptorsDidChange: BindingParser<(NSOutlineView, [NSSortDescriptor]) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(NSOutlineView, [NSSortDescriptor]) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(NSOutlineView, [NSSortDescriptor]) -> Void> in if case .sortDescriptorsDidChange(let x) = binding { return x } else { return nil } }) }
	public static var typeSelectString: BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn?, _ indexPath: IndexPath) -> String?, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ column: NSTableColumn?, _ indexPath: IndexPath) -> String?, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ column: NSTableColumn?, _ indexPath: IndexPath) -> String?> in if case .typeSelectString(let x) = binding { return x } else { return nil } }) }
	public static var updateDraggingItems: BindingParser<(_ outlineView: NSOutlineView, _ forDrag: NSDraggingInfo) -> Void, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ forDrag: NSDraggingInfo) -> Void, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ forDrag: NSDraggingInfo) -> Void> in if case .updateDraggingItems(let x) = binding { return x } else { return nil } }) }
	public static var validateDrop: BindingParser<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ proposedIndexPath: IndexPath?, _ proposedChildIndex: Int) -> NSDragOperation, OutlineView<Binding.NodeDataType>.Binding> { return BindingParser<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ proposedIndexPath: IndexPath?, _ proposedChildIndex: Int) -> NSDragOperation, OutlineView<Binding.NodeDataType>.Binding>(parse: { binding -> Optional<(_ outlineView: NSOutlineView, _ info: NSDraggingInfo, _ proposedIndexPath: IndexPath?, _ proposedChildIndex: Int) -> NSDragOperation> in if case .validateDrop(let x) = binding { return x } else { return nil } }) }
}

#endif
