//
//  CwlTableView_macOS.swift
//  CwlViews
//
//  Created by Matt Gallagher on 28/10/2015.
//  Copyright © 2015 Matt Gallagher ( https://www.cocoawithlove.com ). All rights reserved.
//
//  Permission to use, copy, modify, and/or distribute this software for any purpose with or without
//  fee is hereby granted, provided that the above copyright notice and this permission notice
//  appear in all copies.
//
//  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
//  SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
//  AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
//  NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
//  OF THIS SOFTWARE.
//

#if os(macOS)

extension BindingParser where Binding: TableViewBinding {
	// You can easily convert the `Binding` cases to `BindingParser` using the following Xcode-style regex:
	// Replace: case ([^\(]+)\((.+)\)$
	// With:    public static var $1: BindingParser<$2, TableView<Binding.RowDataType>.Binding> { return BindingParser<$2, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<$2> in if case .$1(let x) = binding { return x } else { return nil } }) }
		
	//	0. Static bindings are applied at construction and are subsequently immutable.
	
	// 1. Value bindings may be applied at construction and may subsequently change.
	public static var allowsColumnReordering: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnReordering(let x) = binding { return x } else { return nil } }) }
	public static var allowsColumnResizing: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnResizing(let x) = binding { return x } else { return nil } }) }
	public static var allowsColumnSelection: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsColumnSelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsEmptySelection: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsEmptySelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsMultipleSelection: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsMultipleSelection(let x) = binding { return x } else { return nil } }) }
	public static var allowsTypeSelect: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .allowsTypeSelect(let x) = binding { return x } else { return nil } }) }
	public static var autosaveName: BindingParser<Dynamic<NSTableView.AutosaveName?>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.AutosaveName?>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.AutosaveName?>> in if case .autosaveName(let x) = binding { return x } else { return nil } }) }
	public static var autosaveTableColumns: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .autosaveTableColumns(let x) = binding { return x } else { return nil } }) }
	public static var backgroundColor: BindingParser<Dynamic<NSColor>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSColor>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSColor>> in if case .backgroundColor(let x) = binding { return x } else { return nil } }) }
	public static var columnAutoresizingStyle: BindingParser<Dynamic<NSTableView.ColumnAutoresizingStyle>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.ColumnAutoresizingStyle>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.ColumnAutoresizingStyle>> in if case .columnAutoresizingStyle(let x) = binding { return x } else { return nil } }) }
	public static var columns: BindingParser<Dynamic<[TableColumn<Binding.RowDataType>]>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<[TableColumn<Binding.RowDataType>]>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<[TableColumn<Binding.RowDataType>]>> in if case .columns(let x) = binding { return x } else { return nil } }) }
	public static var cornerView: BindingParser<Dynamic<ViewConvertible?>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<ViewConvertible?>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<ViewConvertible?>> in if case .cornerView(let x) = binding { return x } else { return nil } }) }
	public static var draggingDestinationFeedbackStyle: BindingParser<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.DraggingDestinationFeedbackStyle>> in if case .draggingDestinationFeedbackStyle(let x) = binding { return x } else { return nil } }) }
	public static var floatsGroupRows: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .floatsGroupRows(let x) = binding { return x } else { return nil } }) }
	public static var gridColor: BindingParser<Dynamic<NSColor>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSColor>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSColor>> in if case .gridColor(let x) = binding { return x } else { return nil } }) }
	public static var gridStyleMask: BindingParser<Dynamic<NSTableView.GridLineStyle>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.GridLineStyle>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.GridLineStyle>> in if case .gridStyleMask(let x) = binding { return x } else { return nil } }) }
	public static var headerView: BindingParser<Dynamic<TableHeaderViewConvertible?>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<TableHeaderViewConvertible?>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<TableHeaderViewConvertible?>> in if case .headerView(let x) = binding { return x } else { return nil } }) }
	public static var intercellSpacing: BindingParser<Dynamic<NSSize>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSSize>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSSize>> in if case .intercellSpacing(let x) = binding { return x } else { return nil } }) }
	public static var rowHeight: BindingParser<Dynamic<CGFloat>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<CGFloat>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<CGFloat>> in if case .rowHeight(let x) = binding { return x } else { return nil } }) }
	public static var rows: BindingParser<Dynamic<TableRowAnimatable<Binding.RowDataType>>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<TableRowAnimatable<Binding.RowDataType>>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<TableRowAnimatable<Binding.RowDataType>>> in if case .rows(let x) = binding { return x } else { return nil } }) }
	public static var rowSizeStyle: BindingParser<Dynamic<NSTableView.RowSizeStyle>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.RowSizeStyle>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.RowSizeStyle>> in if case .rowSizeStyle(let x) = binding { return x } else { return nil } }) }
	public static var selectionHighlightStyle: BindingParser<Dynamic<NSTableView.SelectionHighlightStyle>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSTableView.SelectionHighlightStyle>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSTableView.SelectionHighlightStyle>> in if case .selectionHighlightStyle(let x) = binding { return x } else { return nil } }) }
	public static var userInterfaceLayoutDirection: BindingParser<Dynamic<NSUserInterfaceLayoutDirection>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<NSUserInterfaceLayoutDirection>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<NSUserInterfaceLayoutDirection>> in if case .userInterfaceLayoutDirection(let x) = binding { return x } else { return nil } }) }
	public static var usesAlternatingRowBackgroundColors: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .usesAlternatingRowBackgroundColors(let x) = binding { return x } else { return nil } }) }
	public static var usesAutomaticRowHeights: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .usesAutomaticRowHeights(let x) = binding { return x } else { return nil } }) }
	public static var verticalMotionCanBeginDrag: BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Dynamic<Bool>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Dynamic<Bool>> in if case .verticalMotionCanBeginDrag(let x) = binding { return x } else { return nil } }) }

	// 2. Signal bindings are performed on the object after construction.
	public static var deselectAll: BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .deselectAll(let x) = binding { return x } else { return nil } }) }
	public static var deselectColumn: BindingParser<Signal<NSUserInterfaceItemIdentifier>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier>> in if case .deselectColumn(let x) = binding { return x } else { return nil } }) }
	public static var deselectRow: BindingParser<Signal<Int>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Int>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Int>> in if case .deselectRow(let x) = binding { return x } else { return nil } }) }
	public static var hideRowActions: BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .hideRowActions(let x) = binding { return x } else { return nil } }) }
	public static var hideRows: BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>> in if case .hideRows(let x) = binding { return x } else { return nil } }) }
	public static var highlightColumn: BindingParser<Signal<NSUserInterfaceItemIdentifier?>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier?>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier?>> in if case .highlightColumn(let x) = binding { return x } else { return nil } }) }
	public static var moveColumn: BindingParser<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<(identifier: NSUserInterfaceItemIdentifier, toIndex: Int)>> in if case .moveColumn(let x) = binding { return x } else { return nil } }) }
	public static var scrollColumnToVisible: BindingParser<Signal<NSUserInterfaceItemIdentifier>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<NSUserInterfaceItemIdentifier>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<NSUserInterfaceItemIdentifier>> in if case .scrollColumnToVisible(let x) = binding { return x } else { return nil } }) }
	public static var scrollRowToVisible: BindingParser<Signal<Int>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Int>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Int>> in if case .scrollRowToVisible(let x) = binding { return x } else { return nil } }) }
	public static var selectAll: BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .selectAll(let x) = binding { return x } else { return nil } }) }
	public static var selectColumns: BindingParser<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<(identifiers: Set<NSUserInterfaceItemIdentifier>, byExtendingSelection: Bool)>> in if case .selectColumns(let x) = binding { return x } else { return nil } }) }
	public static var selectRows: BindingParser<Signal<(indexes: IndexSet, byExtendingSelection: Bool)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<(indexes: IndexSet, byExtendingSelection: Bool)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<(indexes: IndexSet, byExtendingSelection: Bool)>> in if case .selectRows(let x) = binding { return x } else { return nil } }) }
	public static var sizeLastColumnToFit: BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .sizeLastColumnToFit(let x) = binding { return x } else { return nil } }) }
	public static var sizeToFit: BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<Void>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<Void>> in if case .sizeToFit(let x) = binding { return x } else { return nil } }) }
	public static var unhideRows: BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<Signal<(indexes: IndexSet, withAnimation: NSTableView.AnimationOptions)>> in if case .unhideRows(let x) = binding { return x } else { return nil } }) }

	// 3. Action bindings are triggered by the object after construction.
	public static var columnMoved: BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<SignalInput<(column: NSUserInterfaceItemIdentifier, oldIndex: Int, newIndex: Int)>> in if case .columnMoved(let x) = binding { return x } else { return nil } }) }
	public static var columnResized: BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>, TableView<Binding.RowDataType>.Binding> { return BindingParser<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<SignalInput<(column: NSUserInterfaceItemIdentifier, oldWidth: CGFloat, newWidth: CGFloat)>> in if case .columnResized(let x) = binding { return x } else { return nil } }) }
	public static var doubleAction: BindingParser<TargetAction, TableView<Binding.RowDataType>.Binding> { return BindingParser<TargetAction, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<TargetAction> in if case .doubleAction(let x) = binding { return x } else { return nil } }) }
	public static var visibleRowsChanged: BindingParser<SignalInput<CountableRange<Int>>, TableView<Binding.RowDataType>.Binding> { return BindingParser<SignalInput<CountableRange<Int>>, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<SignalInput<CountableRange<Int>>> in if case .visibleRowsChanged(let x) = binding { return x } else { return nil } }) }

	// 4. Delegate bindings require synchronous evaluation within the object's context.
	public static var acceptDrop: BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> Bool> in if case .acceptDrop(let x) = binding { return x } else { return nil } }) }
	public static var didClickTableColumn: BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(NSTableView, NSTableColumn) -> Void> in if case .didClickTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var didDragTableColumn: BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(NSTableView, NSTableColumn) -> Void> in if case .didDragTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var draggingSessionEnded: BindingParser<(_ tableView: NSTableView, _ session: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ session: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ session: NSDraggingSession, _ endedAt: NSPoint, _ operation: NSDragOperation) -> Void> in if case .draggingSessionEnded(let x) = binding { return x } else { return nil } }) }
	public static var draggingSessionWillBegin: BindingParser<(_ tableView: NSTableView, _ session: NSDraggingSession, _ willBeginAt: NSPoint, _ forRowIndexes: IndexSet) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ session: NSDraggingSession, _ willBeginAt: NSPoint, _ forRowIndexes: IndexSet) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ session: NSDraggingSession, _ willBeginAt: NSPoint, _ forRowIndexes: IndexSet) -> Void> in if case .draggingSessionWillBegin(let x) = binding { return x } else { return nil } }) }
	public static var groupRowCellConstructor: BindingParser<(Int) -> TableCellViewConvertible, TableView<Binding.RowDataType>.Binding> { return BindingParser<(Int) -> TableCellViewConvertible, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(Int) -> TableCellViewConvertible> in if case .groupRowCellConstructor(let x) = binding { return x } else { return nil } }) }
	public static var heightOfRow: BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> CGFloat, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> CGFloat, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> CGFloat> in if case .heightOfRow(let x) = binding { return x } else { return nil } }) }
	public static var isGroupRow: BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool> in if case .isGroupRow(let x) = binding { return x } else { return nil } }) }
	public static var mouseDownInHeaderOfTableColumn: BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(NSTableView, NSTableColumn) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(NSTableView, NSTableColumn) -> Void> in if case .mouseDownInHeaderOfTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var nextTypeSelectMatch: BindingParser<(_ tableView: NSTableView, _ startRow: Int, _ endRow: Int, _ searchString: String) -> Int, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ startRow: Int, _ endRow: Int, _ searchString: String) -> Int, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ startRow: Int, _ endRow: Int, _ searchString: String) -> Int> in if case .nextTypeSelectMatch(let x) = binding { return x } else { return nil } }) }
	public static var pasteboardWriter: BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> NSPasteboardWriting, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> NSPasteboardWriting, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?) -> NSPasteboardWriting> in if case .pasteboardWriter(let x) = binding { return x } else { return nil } }) }
	public static var rowActionsForRow: BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?, _ edge: NSTableView.RowActionEdge) -> [NSTableViewRowAction], TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?, _ edge: NSTableView.RowActionEdge) -> [NSTableViewRowAction], TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ data: Binding.RowDataType?, _ edge: NSTableView.RowActionEdge) -> [NSTableViewRowAction]> in if case .rowActionsForRow(let x) = binding { return x } else { return nil } }) }
	public static var rowView: BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> TableRowViewConvertible?, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> TableRowViewConvertible?, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> TableRowViewConvertible?> in if case .rowView(let x) = binding { return x } else { return nil } }) }
	public static var selectionDidChange: BindingParser<(Notification) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(Notification) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(Notification) -> Void> in if case .selectionDidChange(let x) = binding { return x } else { return nil } }) }
	public static var selectionIndexesForProposedSelection: BindingParser<(_ tableView: NSTableView, IndexSet) -> IndexSet, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, IndexSet) -> IndexSet, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, IndexSet) -> IndexSet> in if case .selectionIndexesForProposedSelection(let x) = binding { return x } else { return nil } }) }
	public static var selectionShouldChange: BindingParser<(_ tableView: NSTableView) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView) -> Bool> in if case .selectionShouldChange(let x) = binding { return x } else { return nil } }) }
	public static var shouldReorderColumn: BindingParser<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier, _ newIndex: Int) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier, _ newIndex: Int) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier, _ newIndex: Int) -> Bool> in if case .shouldReorderColumn(let x) = binding { return x } else { return nil } }) }
	public static var shouldSelectRow: BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ row: Int, _ rowData: Binding.RowDataType?) -> Bool> in if case .shouldSelectRow(let x) = binding { return x } else { return nil } }) }
	public static var shouldSelectTableColumn: BindingParser<(_ tableView: NSTableView, _ column: NSTableColumn?) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ column: NSTableColumn?) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ column: NSTableColumn?) -> Bool> in if case .shouldSelectTableColumn(let x) = binding { return x } else { return nil } }) }
	public static var shouldTypeSelectForEvent: BindingParser<(_ tableView: NSTableView, _ event: NSEvent, _ searchString: String?) -> Bool, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ event: NSEvent, _ searchString: String?) -> Bool, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ event: NSEvent, _ searchString: String?) -> Bool> in if case .shouldTypeSelectForEvent(let x) = binding { return x } else { return nil } }) }
	public static var sizeToFitWidthOfColumn: BindingParser<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier) -> CGFloat, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier) -> CGFloat, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ column: NSUserInterfaceItemIdentifier) -> CGFloat> in if case .sizeToFitWidthOfColumn(let x) = binding { return x } else { return nil } }) }
	public static var sortDescriptorsDidChange: BindingParser<(NSTableView, [NSSortDescriptor]) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(NSTableView, [NSSortDescriptor]) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(NSTableView, [NSSortDescriptor]) -> Void> in if case .sortDescriptorsDidChange(let x) = binding { return x } else { return nil } }) }
	public static var typeSelectString: BindingParser<(_ tableView: NSTableView, _ cell: TableCell<Binding.RowDataType>) -> String?, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ cell: TableCell<Binding.RowDataType>) -> String?, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ cell: TableCell<Binding.RowDataType>) -> String?> in if case .typeSelectString(let x) = binding { return x } else { return nil } }) }
	public static var updateDraggingItems: BindingParser<(_ tableView: NSTableView, _ forDrag: NSDraggingInfo) -> Void, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ forDrag: NSDraggingInfo) -> Void, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ forDrag: NSDraggingInfo) -> Void> in if case .updateDraggingItems(let x) = binding { return x } else { return nil } }) }
	public static var validateDrop: BindingParser<(_ tableView: NSTableView, _ info: NSDraggingInfo, _ proposedRow: Int, _ proposedDropOperation: NSTableView.DropOperation) -> NSDragOperation, TableView<Binding.RowDataType>.Binding> { return BindingParser<(_ tableView: NSTableView, _ info: NSDraggingInfo, _ proposedRow: Int, _ proposedDropOperation: NSTableView.DropOperation) -> NSDragOperation, TableView<Binding.RowDataType>.Binding>(parse: { binding -> Optional<(_ tableView: NSTableView, _ info: NSDraggingInfo, _ proposedRow: Int, _ proposedDropOperation: NSTableView.DropOperation) -> NSDragOperation> in if case .validateDrop(let x) = binding { return x } else { return nil } }) }
}

#endif
